#ifndef UNISTD_H
#define UNISTD_H

#define __SYSCALL_BASE 9527
#define __NR_SYSCALLS 20


#define SYS_putchar 		((__SYSCALL_BASE ) + (0 ) ) 
#define SYS_getenvid 		((__SYSCALL_BASE ) + (1 ) )
#define SYS_yield			((__SYSCALL_BASE ) + (2 ) )
#define SYS_env_destroy		((__SYSCALL_BASE ) + (3 ) )
#define SYS_set_pgfault_handler	((__SYSCALL_BASE ) + (4 ) )
#define SYS_mem_alloc		((__SYSCALL_BASE ) + (5 ) )
#define SYS_mem_map			((__SYSCALL_BASE ) + (6 ) )
#define SYS_mem_unmap		((__SYSCALL_BASE ) + (7 ) )
#define SYS_env_alloc		((__SYSCALL_BASE ) + (8 ) )
#define SYS_set_env_status	((__SYSCALL_BASE ) + (9 ) )
#define SYS_set_trapframe		((__SYSCALL_BASE ) + (10 ) )
#define SYS_panic			((__SYSCALL_BASE ) + (11 ) )
#define SYS_ipc_can_send		((__SYSCALL_BASE ) + (12 ) )
#define SYS_ipc_recv		((__SYSCALL_BASE ) + (13 ) )
#define SYS_cgetc			((__SYSCALL_BASE ) + (14 ) )
#define SYS_thread_create	((__SYSCALL_BASE ) + (15))
#define SYS_thread_exit		((__SYSCALL_BASE ) + (16))
#define SYS_thread_cancel 	((__SYSCALL_BASE ) + (17))
#define SYS_thread_testcancel ((__SYSCALL_BASE) + (18))
#define SYS_thread_setcancelstate ((__SYSCALL_BASE) + (19))
#define SYS_thread_setcanceltype ((__SYSCALL_BASE) + (20))
#define SYS_thread_detach 		((__SYSCALL_BASE) + (21))
#define SYS_thread_join 		((__SYSCALL_BASE) + (22))
#define SYS_thread_isrunnable 	((__SYSCALL_BASE) + (23))
#define SYS_thread_key_create 	((__SYSCALL_BASE) + (24))
#define SYS_thread_key_delete 	((__SYSCALL_BASE) + (25))
#define SYS_thread_getspecific 	((__SYSCALL_BASE) + (26))
#define SYS_thread_setspecific 	((__SYSCALL_BASE) + (27))
#define SYS_thread_cleanup_push ((__SYSCALL_BASE) + (28))
#define SYS_thread_cleanup_pop 	((__SYSCALL_BASE) + (29))
#define SYS_thread_getatfork 	((__SYSCALL_BASE) + (30))
#define SYS_thread_setatfork	((__SYSCALL_BASE) + (31))
#define SYS_sem_P 				((__SYSCALL_BASE) + (32))
#define SYS_sem_try 			((__SYSCALL_BASE) + (33))
#define SYS_sem_V 				((__SYSCALL_BASE) + (34))
#define SYS_sem_get 			((__SYSCALL_BASE) + (35))
#define SYS_named_sem_create 	((__SYSCALL_BASE) + (36))
#define SYS_named_sem_open 		((__SYSCALL_BASE) + (37))
#define SYS_named_sem_unlink 	((__SYSCALL_BASE) + (38))
#endif
